// Automatically generated by MockGen. DO NOT EDIT!
// Source: request.go

package mock_gomock_sample

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of Request interface
type MockRequest struct {
	ctrl     *gomock.Controller
	recorder *_MockRequestRecorder
}

// Recorder for MockRequest (not exported)
type _MockRequestRecorder struct {
	mock *MockRequest
}

func NewMockRequest(ctrl *gomock.Controller) *MockRequest {
	mock := &MockRequest{ctrl: ctrl}
	mock.recorder = &_MockRequestRecorder{mock}
	return mock
}

func (_m *MockRequest) EXPECT() *_MockRequestRecorder {
	return _m.recorder
}

func (_m *MockRequest) DoRequest(url string) int {
	ret := _m.ctrl.Call(_m, "DoRequest", url)
	ret0, _ := ret[0].(int)
	return ret0
}

func (_mr *_MockRequestRecorder) DoRequest(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DoRequest", arg0)
}
