// Code generated by protoc-gen-go. DO NOT EDIT.
// source: address.proto

/*
Package address is a generated protocol buffer package.

It is generated from these files:
	address.proto

It has these top-level messages:
	GeocoderRequest
	GeocoderReply
*/
package address

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GeocoderRequest struct {
	Lat int32 `protobuf:"varint,1,opt,name=lat" json:"lat,omitempty"`
	Lon int32 `protobuf:"varint,2,opt,name=lon" json:"lon,omitempty"`
}

func (m *GeocoderRequest) Reset()                    { *m = GeocoderRequest{} }
func (m *GeocoderRequest) String() string            { return proto.CompactTextString(m) }
func (*GeocoderRequest) ProtoMessage()               {}
func (*GeocoderRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GeocoderRequest) GetLat() int32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *GeocoderRequest) GetLon() int32 {
	if m != nil {
		return m.Lon
	}
	return 0
}

type GeocoderReply struct {
	Address string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
}

func (m *GeocoderReply) Reset()                    { *m = GeocoderReply{} }
func (m *GeocoderReply) String() string            { return proto.CompactTextString(m) }
func (*GeocoderReply) ProtoMessage()               {}
func (*GeocoderReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GeocoderReply) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func init() {
	proto.RegisterType((*GeocoderRequest)(nil), "address.GeocoderRequest")
	proto.RegisterType((*GeocoderReply)(nil), "address.GeocoderReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Geocoder service

type GeocoderClient interface {
	GetAddress(ctx context.Context, in *GeocoderRequest, opts ...grpc.CallOption) (*GeocoderReply, error)
	GetAddressError(ctx context.Context, in *GeocoderRequest, opts ...grpc.CallOption) (*GeocoderReply, error)
}

type geocoderClient struct {
	cc *grpc.ClientConn
}

func NewGeocoderClient(cc *grpc.ClientConn) GeocoderClient {
	return &geocoderClient{cc}
}

func (c *geocoderClient) GetAddress(ctx context.Context, in *GeocoderRequest, opts ...grpc.CallOption) (*GeocoderReply, error) {
	out := new(GeocoderReply)
	err := grpc.Invoke(ctx, "/address.Geocoder/GetAddress", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geocoderClient) GetAddressError(ctx context.Context, in *GeocoderRequest, opts ...grpc.CallOption) (*GeocoderReply, error) {
	out := new(GeocoderReply)
	err := grpc.Invoke(ctx, "/address.Geocoder/GetAddressError", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Geocoder service

type GeocoderServer interface {
	GetAddress(context.Context, *GeocoderRequest) (*GeocoderReply, error)
	GetAddressError(context.Context, *GeocoderRequest) (*GeocoderReply, error)
}

func RegisterGeocoderServer(s *grpc.Server, srv GeocoderServer) {
	s.RegisterService(&_Geocoder_serviceDesc, srv)
}

func _Geocoder_GetAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeocoderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeocoderServer).GetAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/address.Geocoder/GetAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeocoderServer).GetAddress(ctx, req.(*GeocoderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Geocoder_GetAddressError_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeocoderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeocoderServer).GetAddressError(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/address.Geocoder/GetAddressError",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeocoderServer).GetAddressError(ctx, req.(*GeocoderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Geocoder_serviceDesc = grpc.ServiceDesc{
	ServiceName: "address.Geocoder",
	HandlerType: (*GeocoderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAddress",
			Handler:    _Geocoder_GetAddress_Handler,
		},
		{
			MethodName: "GetAddressError",
			Handler:    _Geocoder_GetAddressError_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "address.proto",
}

func init() { proto.RegisterFile("address.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 204 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x4c, 0x49, 0x29,
	0x4a, 0x2d, 0x2e, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0x4c, 0xb9,
	0xf8, 0xdd, 0x53, 0xf3, 0x93, 0xf3, 0x53, 0x52, 0x8b, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b,
	0x84, 0x04, 0xb8, 0x98, 0x73, 0x12, 0x4b, 0x24, 0x18, 0x15, 0x18, 0x35, 0x58, 0x83, 0x40, 0x4c,
	0xb0, 0x48, 0x7e, 0x9e, 0x04, 0x13, 0x54, 0x24, 0x3f, 0x4f, 0x49, 0x93, 0x8b, 0x17, 0xa1, 0xad,
	0x20, 0xa7, 0x52, 0x48, 0x82, 0x0b, 0x66, 0x24, 0x58, 0x23, 0x67, 0x10, 0x8c, 0x6b, 0x34, 0x99,
	0x91, 0x8b, 0x03, 0xa6, 0x56, 0xc8, 0x81, 0x8b, 0xcb, 0x3d, 0xb5, 0xc4, 0x11, 0x22, 0x25, 0x24,
	0xa1, 0x07, 0x73, 0x15, 0x9a, 0x1b, 0xa4, 0xc4, 0xb0, 0xc8, 0x14, 0xe4, 0x54, 0x2a, 0x31, 0x08,
	0xb9, 0x82, 0x1c, 0x0c, 0x33, 0xc1, 0xb5, 0xa8, 0x28, 0xbf, 0x88, 0x1c, 0x63, 0x9c, 0x0c, 0xb8,
	0xa4, 0x33, 0xf3, 0xf5, 0xd2, 0x8b, 0x0a, 0x92, 0xf5, 0x52, 0x2b, 0x12, 0x73, 0x0b, 0x72, 0x52,
	0x8b, 0xf5, 0x32, 0x52, 0x73, 0x72, 0xf2, 0xcb, 0xf3, 0x8b, 0x72, 0x52, 0x9c, 0xf8, 0x3d, 0x40,
	0xec, 0x70, 0x10, 0x3b, 0x00, 0x14, 0x60, 0x01, 0x8c, 0x49, 0x6c, 0xe0, 0x90, 0x33, 0x06, 0x04,
	0x00, 0x00, 0xff, 0xff, 0x5f, 0xda, 0xd0, 0x21, 0x4a, 0x01, 0x00, 0x00,
}
